// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmUYndKBu0pE_FqcTsHri-eVz4Ipflvnk',
    appId: '1:366547948318:web:fee0c7904568aae2912f0f',
    messagingSenderId: '366547948318',
    projectId: 'tcc-app-a94db',
    authDomain: 'tcc-app-a94db.firebaseapp.com',
    storageBucket: 'tcc-app-a94db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXw_yjNgo3eIa1CAklPeKsR-paVArnvrA',
    appId: '1:366547948318:android:13a11b59efdd7c15912f0f',
    messagingSenderId: '366547948318',
    projectId: 'tcc-app-a94db',
    storageBucket: 'tcc-app-a94db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJeD9ct5624YlXzPlSGkPo8uIWTnp0aMA',
    appId: '1:366547948318:ios:c2e7621b027c2ab5912f0f',
    messagingSenderId: '366547948318',
    projectId: 'tcc-app-a94db',
    storageBucket: 'tcc-app-a94db.firebasestorage.app',
    iosBundleId: 'com.example.appEstacaoIrrigacao',
  );
}
